### ISSUE TITLE
Planning for Version 0.1.0

### ISSUE THREAD

**Issue by murillocg** [murillocg/sense-app#1]
- [ ] Add ReactJS to the project #2 
- [x] Create an endpoint to get all events #3 
- [ ] Setup Travis to build and deploy the application whenever the branch master is updated #5
